INSERT INTO roles (code, name, scope, is_system, description) VALUES
('SYSTEM_ADMIN', 'System Administrator', 'SYSTEM', true, 'Full platform and permission administration access'),
('OPS_ADMIN', 'Ops Administrator', 'SYSTEM', true, 'Operational administration for payments, refunds, providers, and risk workflows'),
('OPS_SUPPORT', 'Ops Support', 'SYSTEM', true, 'Read-mostly operational support with selected risk actions'),
('MERCHANT_OWNER', 'Merchant Owner', 'MERCHANT', true, 'Full merchant workspace access'),
('MERCHANT_DEVELOPER', 'Merchant Developer', 'MERCHANT', true, 'Developer access for API keys, webhooks, and integration testing'),
('MERCHANT_FINANCE', 'Merchant Finance', 'MERCHANT', true, 'Finance access for payments, refunds, fiat ramp, and exports'),
('MERCHANT_SUPPORT', 'Merchant Support', 'MERCHANT', true, 'Support access for payment and refund lookup'),
('MERCHANT_VIEWER', 'Merchant Viewer', 'MERCHANT', true, 'Read-only merchant workspace access')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    scope = EXCLUDED.scope,
    is_system = EXCLUDED.is_system,
    description = EXCLUDED.description;

WITH role_permission_seed(role_code, permission_code) AS (
    VALUES
    -- Platform super admin.
    ('SYSTEM_ADMIN', 'merchant:read'),
    ('SYSTEM_ADMIN', 'merchant:create'),
    ('SYSTEM_ADMIN', 'merchant:update'),
    ('SYSTEM_ADMIN', 'merchant:activate'),
    ('SYSTEM_ADMIN', 'merchant:suspend'),
    ('SYSTEM_ADMIN', 'merchant_user:read'),
    ('SYSTEM_ADMIN', 'merchant_user:invite'),
    ('SYSTEM_ADMIN', 'merchant_user:update'),
    ('SYSTEM_ADMIN', 'merchant_user:disable'),
    ('SYSTEM_ADMIN', 'api_key:read'),
    ('SYSTEM_ADMIN', 'api_key:create'),
    ('SYSTEM_ADMIN', 'api_key:rotate'),
    ('SYSTEM_ADMIN', 'api_key:revoke'),
    ('SYSTEM_ADMIN', 'webhook:read'),
    ('SYSTEM_ADMIN', 'webhook:update'),
    ('SYSTEM_ADMIN', 'webhook:test'),
    ('SYSTEM_ADMIN', 'webhook:replay'),
    ('SYSTEM_ADMIN', 'payment_order:read'),
    ('SYSTEM_ADMIN', 'payment_order:create'),
    ('SYSTEM_ADMIN', 'payment_order:export'),
    ('SYSTEM_ADMIN', 'crypto_payment:read'),
    ('SYSTEM_ADMIN', 'crypto_payment:create'),
    ('SYSTEM_ADMIN', 'crypto_payment:confirm'),
    ('SYSTEM_ADMIN', 'crypto_payment:fail'),
    ('SYSTEM_ADMIN', 'refund:read'),
    ('SYSTEM_ADMIN', 'refund:create'),
    ('SYSTEM_ADMIN', 'refund:approve'),
    ('SYSTEM_ADMIN', 'refund:retry'),
    ('SYSTEM_ADMIN', 'fiat_ramp:quote'),
    ('SYSTEM_ADMIN', 'fiat_ramp:create'),
    ('SYSTEM_ADMIN', 'fiat_ramp:read'),
    ('SYSTEM_ADMIN', 'fiat_ramp:operate'),
    ('SYSTEM_ADMIN', 'orphan:read'),
    ('SYSTEM_ADMIN', 'orphan:resolve'),
    ('SYSTEM_ADMIN', 'orphan:ignore'),
    ('SYSTEM_ADMIN', 'orphan:compensate'),
    ('SYSTEM_ADMIN', 'webhook_dlq:read'),
    ('SYSTEM_ADMIN', 'webhook_dlq:replay'),
    ('SYSTEM_ADMIN', 'webhook_dlq:ignore'),
    ('SYSTEM_ADMIN', 'ops_dashboard:read'),
    ('SYSTEM_ADMIN', 'provider:read'),
    ('SYSTEM_ADMIN', 'provider:update'),
    ('SYSTEM_ADMIN', 'provider:disable'),
    ('SYSTEM_ADMIN', 'provider:enable'),
    ('SYSTEM_ADMIN', 'permission:read'),
    ('SYSTEM_ADMIN', 'permission:manage'),
    ('SYSTEM_ADMIN', 'role:read'),
    ('SYSTEM_ADMIN', 'role:manage'),
    ('SYSTEM_ADMIN', 'user_role:read'),
    ('SYSTEM_ADMIN', 'user_role:grant'),
    ('SYSTEM_ADMIN', 'user_role:revoke'),
    ('SYSTEM_ADMIN', 'audit:read'),

    -- Ops admin.
    ('OPS_ADMIN', 'merchant:read'),
    ('OPS_ADMIN', 'merchant:update'),
    ('OPS_ADMIN', 'merchant:activate'),
    ('OPS_ADMIN', 'merchant:suspend'),
    ('OPS_ADMIN', 'payment_order:read'),
    ('OPS_ADMIN', 'payment_order:export'),
    ('OPS_ADMIN', 'crypto_payment:read'),
    ('OPS_ADMIN', 'crypto_payment:confirm'),
    ('OPS_ADMIN', 'crypto_payment:fail'),
    ('OPS_ADMIN', 'refund:read'),
    ('OPS_ADMIN', 'refund:approve'),
    ('OPS_ADMIN', 'refund:retry'),
    ('OPS_ADMIN', 'fiat_ramp:read'),
    ('OPS_ADMIN', 'fiat_ramp:operate'),
    ('OPS_ADMIN', 'orphan:read'),
    ('OPS_ADMIN', 'orphan:resolve'),
    ('OPS_ADMIN', 'orphan:ignore'),
    ('OPS_ADMIN', 'orphan:compensate'),
    ('OPS_ADMIN', 'webhook_dlq:read'),
    ('OPS_ADMIN', 'webhook_dlq:replay'),
    ('OPS_ADMIN', 'webhook_dlq:ignore'),
    ('OPS_ADMIN', 'ops_dashboard:read'),
    ('OPS_ADMIN', 'provider:read'),
    ('OPS_ADMIN', 'provider:update'),
    ('OPS_ADMIN', 'provider:disable'),
    ('OPS_ADMIN', 'provider:enable'),
    ('OPS_ADMIN', 'audit:read'),

    -- Ops support.
    ('OPS_SUPPORT', 'merchant:read'),
    ('OPS_SUPPORT', 'payment_order:read'),
    ('OPS_SUPPORT', 'crypto_payment:read'),
    ('OPS_SUPPORT', 'refund:read'),
    ('OPS_SUPPORT', 'fiat_ramp:read'),
    ('OPS_SUPPORT', 'orphan:read'),
    ('OPS_SUPPORT', 'orphan:resolve'),
    ('OPS_SUPPORT', 'orphan:ignore'),
    ('OPS_SUPPORT', 'webhook_dlq:read'),
    ('OPS_SUPPORT', 'webhook_dlq:replay'),
    ('OPS_SUPPORT', 'ops_dashboard:read'),
    ('OPS_SUPPORT', 'provider:read'),

    -- Merchant owner.
    ('MERCHANT_OWNER', 'merchant:read'),
    ('MERCHANT_OWNER', 'merchant:update'),
    ('MERCHANT_OWNER', 'merchant_user:read'),
    ('MERCHANT_OWNER', 'merchant_user:invite'),
    ('MERCHANT_OWNER', 'merchant_user:update'),
    ('MERCHANT_OWNER', 'merchant_user:disable'),
    ('MERCHANT_OWNER', 'api_key:read'),
    ('MERCHANT_OWNER', 'api_key:create'),
    ('MERCHANT_OWNER', 'api_key:rotate'),
    ('MERCHANT_OWNER', 'api_key:revoke'),
    ('MERCHANT_OWNER', 'webhook:read'),
    ('MERCHANT_OWNER', 'webhook:update'),
    ('MERCHANT_OWNER', 'webhook:test'),
    ('MERCHANT_OWNER', 'webhook:replay'),
    ('MERCHANT_OWNER', 'payment_order:read'),
    ('MERCHANT_OWNER', 'payment_order:create'),
    ('MERCHANT_OWNER', 'payment_order:export'),
    ('MERCHANT_OWNER', 'crypto_payment:read'),
    ('MERCHANT_OWNER', 'crypto_payment:create'),
    ('MERCHANT_OWNER', 'refund:read'),
    ('MERCHANT_OWNER', 'refund:create'),
    ('MERCHANT_OWNER', 'fiat_ramp:quote'),
    ('MERCHANT_OWNER', 'fiat_ramp:create'),
    ('MERCHANT_OWNER', 'fiat_ramp:read'),
    ('MERCHANT_OWNER', 'audit:read'),

    -- Merchant developer.
    ('MERCHANT_DEVELOPER', 'merchant:read'),
    ('MERCHANT_DEVELOPER', 'api_key:read'),
    ('MERCHANT_DEVELOPER', 'api_key:create'),
    ('MERCHANT_DEVELOPER', 'api_key:rotate'),
    ('MERCHANT_DEVELOPER', 'webhook:read'),
    ('MERCHANT_DEVELOPER', 'webhook:update'),
    ('MERCHANT_DEVELOPER', 'webhook:test'),
    ('MERCHANT_DEVELOPER', 'payment_order:read'),
    ('MERCHANT_DEVELOPER', 'payment_order:create'),
    ('MERCHANT_DEVELOPER', 'crypto_payment:read'),
    ('MERCHANT_DEVELOPER', 'crypto_payment:create'),
    ('MERCHANT_DEVELOPER', 'fiat_ramp:quote'),
    ('MERCHANT_DEVELOPER', 'fiat_ramp:create'),
    ('MERCHANT_DEVELOPER', 'fiat_ramp:read'),

    -- Merchant finance.
    ('MERCHANT_FINANCE', 'merchant:read'),
    ('MERCHANT_FINANCE', 'payment_order:read'),
    ('MERCHANT_FINANCE', 'payment_order:create'),
    ('MERCHANT_FINANCE', 'payment_order:export'),
    ('MERCHANT_FINANCE', 'refund:read'),
    ('MERCHANT_FINANCE', 'refund:create'),
    ('MERCHANT_FINANCE', 'fiat_ramp:quote'),
    ('MERCHANT_FINANCE', 'fiat_ramp:create'),
    ('MERCHANT_FINANCE', 'fiat_ramp:read'),
    ('MERCHANT_FINANCE', 'audit:read'),

    -- Merchant support.
    ('MERCHANT_SUPPORT', 'merchant:read'),
    ('MERCHANT_SUPPORT', 'payment_order:read'),
    ('MERCHANT_SUPPORT', 'refund:read'),
    ('MERCHANT_SUPPORT', 'fiat_ramp:read'),
    ('MERCHANT_SUPPORT', 'webhook:read'),

    -- Merchant viewer.
    ('MERCHANT_VIEWER', 'merchant:read'),
    ('MERCHANT_VIEWER', 'merchant_user:read'),
    ('MERCHANT_VIEWER', 'api_key:read'),
    ('MERCHANT_VIEWER', 'webhook:read'),
    ('MERCHANT_VIEWER', 'payment_order:read'),
    ('MERCHANT_VIEWER', 'crypto_payment:read'),
    ('MERCHANT_VIEWER', 'refund:read'),
    ('MERCHANT_VIEWER', 'fiat_ramp:read')
)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM role_permission_seed seed
JOIN roles r ON r.code = seed.role_code
JOIN permissions p ON p.code = seed.permission_code
ON CONFLICT (role_id, permission_id) DO NOTHING;
