-- Merchant portal login users (M5)
-- Note: portable types instead of PostgreSQL aliases TIMESTAMPTZ/BIGSERIAL so the
-- script also applies on H2 (PostgreSQL compatibility mode) of the local 'h2'
-- profile; semantics are identical on PostgreSQL. Guarded by H2MigrationCompatibilityTest.
CREATE TABLE merchant_users (
    user_id       VARCHAR(36) PRIMARY KEY,
    email         VARCHAR(256) UNIQUE NOT NULL,
    password_hash VARCHAR(256),
    display_name  VARCHAR(128) NOT NULL,
    status        VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- User-merchant membership with role (M5)
CREATE TABLE merchant_user_memberships (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id VARCHAR(64) NOT NULL REFERENCES merchant_profiles(merchant_id),
    user_id     VARCHAR(36) NOT NULL REFERENCES merchant_users(user_id),
    role_code   VARCHAR(64) NOT NULL,
    status      VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (merchant_id, user_id)
);

CREATE INDEX idx_merchant_user_memberships_user ON merchant_user_memberships(user_id);
CREATE INDEX idx_merchant_user_memberships_merchant ON merchant_user_memberships(merchant_id);
